import React, { Component } from "react";
import Card from "./Card";
import CardDetail from "./CardDetail";
import "./App.css";

class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            heroes: [
                {
                    id: 1,
                    name: "npc_dota_hero_antimage",
                    localized_name: "Anti-Mage",
                    primary_attr: "agi",
                    attack_type: "Melee",
                    roles: ["Carry", "Escape", "Nuker"],
                    img: "/apps/dota2/images/heroes/antimage_full.png?",
                    icon: "/apps/dota2/images/heroes/antimage_icon.png",
                    base_health: 200,
                    base_health_regen: 0.25,
                    base_mana: 75,
                    base_mana_regen: 0,
                    base_armor: -1,
                    base_mr: 25,
                    base_attack_min: 29,
                    base_attack_max: 33,
                    base_str: 23,
                    base_agi: 24,
                    base_int: 12,
                    str_gain: 1.3,
                    agi_gain: 2.8,
                    int_gain: 1.8,
                    attack_range: 150,
                    projectile_speed: 0,
                    attack_rate: 1.4,
                    move_speed: 310,
                    turn_rate: 0.5,
                    cm_enabled: true,
                    legs: 2,
                    hero_id: 1,
                    turbo_picks: 157645,
                    turbo_wins: 82792,
                    pro_ban: 504,
                    pro_win: 59,
                    pro_pick: 122,
                    "1_pick": 18287,
                    "1_win": 9465,
                    "2_pick": 42181,
                    "2_win": 21520,
                    "3_pick": 60851,
                    "3_win": 31417,
                    "4_pick": 62687,
                    "4_win": 32309,
                    "5_pick": 42515,
                    "5_win": 21770,
                    "6_pick": 19899,
                    "6_win": 10134,
                    "7_pick": 8239,
                    "7_win": 4110,
                    "8_pick": 1873,
                    "8_win": 904,
                    null_pick: 2369165,
                    null_win: 0,
                },
                {
                    id: 2,
                    name: "npc_dota_hero_axe",
                    localized_name: "Axe",
                    primary_attr: "str",
                    attack_type: "Melee",
                    roles: ["Initiator", "Durable", "Disabler", "Jungler"],
                    img: "/apps/dota2/images/heroes/axe_full.png?",
                    icon: "/apps/dota2/images/heroes/axe_icon.png",
                    base_health: 200,
                    base_health_regen: 2.75,
                    base_mana: 75,
                    base_mana_regen: 0,
                    base_armor: -1,
                    base_mr: 25,
                    base_attack_min: 27,
                    base_attack_max: 31,
                    base_str: 25,
                    base_agi: 20,
                    base_int: 18,
                    str_gain: 3.4,
                    agi_gain: 2.2,
                    int_gain: 1.6,
                    attack_range: 150,
                    projectile_speed: 900,
                    attack_rate: 1.7,
                    move_speed: 310,
                    turn_rate: 0.6,
                    cm_enabled: true,
                    legs: 2,
                    hero_id: 2,
                    turbo_picks: 117329,
                    turbo_wins: 58880,
                    pro_ban: 119,
                    pro_win: 47,
                    pro_pick: 116,
                    "1_pick": 16281,
                    "1_win": 8256,
                    "2_pick": 36607,
                    "2_win": 18645,
                    "3_pick": 51197,
                    "3_win": 25855,
                    "4_pick": 50432,
                    "4_win": 25545,
                    "5_pick": 32711,
                    "5_win": 16573,
                    "6_pick": 14492,
                    "6_win": 7358,
                    "7_pick": 5689,
                    "7_win": 2833,
                    "8_pick": 1084,
                    "8_win": 522,
                    null_pick: 1858445,
                    null_win: 0,
                },
                {
                    id: 3,
                    name: "npc_dota_hero_bane",
                    localized_name: "Bane",
                    primary_attr: "int",
                    attack_type: "Ranged",
                    roles: ["Support", "Disabler", "Nuker", "Durable"],
                    img: "/apps/dota2/images/heroes/bane_full.png?",
                    icon: "/apps/dota2/images/heroes/bane_icon.png",
                    base_health: 200,
                    base_health_regen: null,
                    base_mana: 75,
                    base_mana_regen: 0,
                    base_armor: 1,
                    base_mr: 25,
                    base_attack_min: 35,
                    base_attack_max: 41,
                    base_str: 22,
                    base_agi: 22,
                    base_int: 22,
                    str_gain: 2.6,
                    agi_gain: 2.6,
                    int_gain: 2.6,
                    attack_range: 400,
                    projectile_speed: 900,
                    attack_rate: 1.7,
                    move_speed: 305,
                    turn_rate: 0.6,
                    cm_enabled: true,
                    legs: 4,
                    hero_id: 3,
                    turbo_picks: 25934,
                    turbo_wins: 12053,
                    pro_ban: 9,
                    pro_win: 17,
                    pro_pick: 35,
                    "1_pick": 3231,
                    "1_win": 1536,
                    "2_pick": 7364,
                    "2_win": 3657,
                    "3_pick": 11115,
                    "3_win": 5532,
                    "4_pick": 12354,
                    "4_win": 6324,
                    "5_pick": 9668,
                    "5_win": 5101,
                    "6_pick": 5172,
                    "6_win": 2754,
                    "7_pick": 2551,
                    "7_win": 1342,
                    "8_pick": 926,
                    "8_win": 491,
                    null_pick: 668667,
                    null_win: 0,
                },
            ],
            current_heroes: {},
        };
    }
    render() {
        return (
            <div className="App">
                <Card value={this.state.heroes[0]} />
                <CardDetail value={this.state.heroes[0]} />
            </div>
        );
    }
}

export default App;
